version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- cmd: dotnet restore .\WinterSpine.IdentityServer\WinterSpine.IdentityServer.csproj
build:
  project: .\WinterSpine.IdentityServer.sln
  publish_wap: true
  verbosity: minimal
after_build:
- cmd: dotnet publish .\WinterSpine.IdentityServer -o ..\Artifacts\Publish\WinterSpine.IdentityServer -c Debug
artifacts:
- path: Artifacts\Publish\WinterSpine.IdentityServer
  name: WinterSpine.IdentityServer
  type: WebDeployPackage
deploy:
- provider: WebDeploy
  server: https://winterspine-identityserver.scm.azurewebsites.net:443/msdeploy.axd?site=WinterSpine-IdentityServer
  website: WinterSpine-IdentityServer
  username: $WinterSpine-IdentityServer
  password:
    secure: tMHSmRwYSO/0dFqXWtxCeYVq0zWBwlU579KaEIwGTKLvt+GOMwhNymvyVnJnWbG7IqcAfel4jH29jnLd/IWTfA==
  artifact: WinterSpine.IdentityServer
  aspnet_core: true
  remove_files: true
  on:
    branch: master